project:
  type: website
  output-dir: docs

website:
  title: "Diverse Data Hub"
  navbar:
    left:
      - href: index.qmd
        text: Welcome
      - href: website_files/datasets.qmd
        text: Datasets
  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    background: "rgb(97, 179, 230)"
  sidebar:
    logo: "website_files/img/logo.png"
    style: "floating"
    search: false
    align: center
    tools: 
      - icon: github
        href: https://github.com/diverse-data-hub
    collapse-level: 1
    contents:
      - section: "Datasets"
        contents:
          - text: "Women's March Madness"
            href: "https://diverse-data-hub.github.io/website_files/description_pages/marchmadness.html"
          - text: "Wildfire"
            href: "https://diverse-data-hub.github.io/website_files/description_pages/wildfire.html"
          - text: "How Couples Meet and Stay Together"
            href: "https://diverse-data-hub.github.io/website_files/description_pages/hcmst.html"
      - text: "CRAN Page (TBD)"
        href: ""
      - text: "Report an Issue"
        href: "https://github.com/diverse-data-hub/diversedata/issues"
      - text: "License (TBD)"
        href: ""
      - text: "Citation (TBD)"
        href: "https://diverse-data-hub.github.io/website_files/citation.html"
      - section: "Owners"
        contents:
          - text: "Katie Burak PhD"
            href: "https://github.com/katieburak"
          - text: "Elham E Khoda"
            href: "https://github.com/elhamekhoda"
      - section: "Collaborators"
        contents:
          - text: "Francisco Ramirez"
            href: "https://github.com/fraramfra"
          - text: "Azin Piran"
            href: "https://github.com/AzinPiran"
          - text: "Siddarth Subrahmanian"
            href: "https://github.com/siddart-1"

format:
  html:
    theme:
      - minty
      - website_files/styles.scss
    css: website_files/styles.css
    page-layout: full



