#To create environment from scratch:
#conda create -n mds_capstone_v1 -c conda-forge python pandas jupyterlab altair matplotlib

#To create environment.yaml:
#conda env export -f environment.yaml --from-history

#To create envirnment from yaml file:
#conda env create --file environment.yaml

#To delete environment:
#conda env remove -n mds_capstone_v1

#To activate environment:
#conda activate mds_capstone_v1

name: mds_capstone_v1
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=2.2.3
  - altair=5.5.0
  - jupyterlab=4.4.1
  - python=3.13.3
  - matplotlib=3.10.1
  - r-base
  - r-brant
  - r-tidyverse
  - r-knitr
  - r-readr
  - r-dplyr
  - r-ggplot2